// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.1
// source: learn.proto

package protogen

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	LearnService_Hello_FullMethodName      = "/LearnService/Hello"
	LearnService_Add_FullMethodName        = "/LearnService/Add"
	LearnService_StockPrice_FullMethodName = "/LearnService/StockPrice"
)

// LearnServiceClient is the client API for LearnService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LearnServiceClient interface {
	Hello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error)
	Add(ctx context.Context, opts ...grpc.CallOption) (LearnService_AddClient, error)
	StockPrice(ctx context.Context, in *StockRequest, opts ...grpc.CallOption) (LearnService_StockPriceClient, error)
}

type learnServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLearnServiceClient(cc grpc.ClientConnInterface) LearnServiceClient {
	return &learnServiceClient{cc}
}

func (c *learnServiceClient) Hello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error) {
	out := new(HelloResponse)
	err := c.cc.Invoke(ctx, LearnService_Hello_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *learnServiceClient) Add(ctx context.Context, opts ...grpc.CallOption) (LearnService_AddClient, error) {
	stream, err := c.cc.NewStream(ctx, &LearnService_ServiceDesc.Streams[0], LearnService_Add_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &learnServiceAddClient{stream}
	return x, nil
}

type LearnService_AddClient interface {
	Send(*AddRequest) error
	CloseAndRecv() (*AddResponse, error)
	grpc.ClientStream
}

type learnServiceAddClient struct {
	grpc.ClientStream
}

func (x *learnServiceAddClient) Send(m *AddRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *learnServiceAddClient) CloseAndRecv() (*AddResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(AddResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *learnServiceClient) StockPrice(ctx context.Context, in *StockRequest, opts ...grpc.CallOption) (LearnService_StockPriceClient, error) {
	stream, err := c.cc.NewStream(ctx, &LearnService_ServiceDesc.Streams[1], LearnService_StockPrice_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &learnServiceStockPriceClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type LearnService_StockPriceClient interface {
	Recv() (*StockResponse, error)
	grpc.ClientStream
}

type learnServiceStockPriceClient struct {
	grpc.ClientStream
}

func (x *learnServiceStockPriceClient) Recv() (*StockResponse, error) {
	m := new(StockResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// LearnServiceServer is the server API for LearnService service.
// All implementations must embed UnimplementedLearnServiceServer
// for forward compatibility
type LearnServiceServer interface {
	Hello(context.Context, *HelloRequest) (*HelloResponse, error)
	Add(LearnService_AddServer) error
	StockPrice(*StockRequest, LearnService_StockPriceServer) error
	mustEmbedUnimplementedLearnServiceServer()
}

// UnimplementedLearnServiceServer must be embedded to have forward compatible implementations.
type UnimplementedLearnServiceServer struct {
}

func (UnimplementedLearnServiceServer) Hello(context.Context, *HelloRequest) (*HelloResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Hello not implemented")
}
func (UnimplementedLearnServiceServer) Add(LearnService_AddServer) error {
	return status.Errorf(codes.Unimplemented, "method Add not implemented")
}
func (UnimplementedLearnServiceServer) StockPrice(*StockRequest, LearnService_StockPriceServer) error {
	return status.Errorf(codes.Unimplemented, "method StockPrice not implemented")
}
func (UnimplementedLearnServiceServer) mustEmbedUnimplementedLearnServiceServer() {}

// UnsafeLearnServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LearnServiceServer will
// result in compilation errors.
type UnsafeLearnServiceServer interface {
	mustEmbedUnimplementedLearnServiceServer()
}

func RegisterLearnServiceServer(s grpc.ServiceRegistrar, srv LearnServiceServer) {
	s.RegisterService(&LearnService_ServiceDesc, srv)
}

func _LearnService_Hello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LearnServiceServer).Hello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LearnService_Hello_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LearnServiceServer).Hello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LearnService_Add_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(LearnServiceServer).Add(&learnServiceAddServer{stream})
}

type LearnService_AddServer interface {
	SendAndClose(*AddResponse) error
	Recv() (*AddRequest, error)
	grpc.ServerStream
}

type learnServiceAddServer struct {
	grpc.ServerStream
}

func (x *learnServiceAddServer) SendAndClose(m *AddResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *learnServiceAddServer) Recv() (*AddRequest, error) {
	m := new(AddRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _LearnService_StockPrice_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StockRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LearnServiceServer).StockPrice(m, &learnServiceStockPriceServer{stream})
}

type LearnService_StockPriceServer interface {
	Send(*StockResponse) error
	grpc.ServerStream
}

type learnServiceStockPriceServer struct {
	grpc.ServerStream
}

func (x *learnServiceStockPriceServer) Send(m *StockResponse) error {
	return x.ServerStream.SendMsg(m)
}

// LearnService_ServiceDesc is the grpc.ServiceDesc for LearnService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LearnService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "LearnService",
	HandlerType: (*LearnServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Hello",
			Handler:    _LearnService_Hello_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Add",
			Handler:       _LearnService_Add_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "StockPrice",
			Handler:       _LearnService_StockPrice_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "learn.proto",
}
