// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.1
// source: learn.proto

package protogen

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	LearnService_Hello_FullMethodName = "/LearnService/Hello"
)

// LearnServiceClient is the client API for LearnService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LearnServiceClient interface {
	Hello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error)
}

type learnServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLearnServiceClient(cc grpc.ClientConnInterface) LearnServiceClient {
	return &learnServiceClient{cc}
}

func (c *learnServiceClient) Hello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error) {
	out := new(HelloResponse)
	err := c.cc.Invoke(ctx, LearnService_Hello_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LearnServiceServer is the server API for LearnService service.
// All implementations must embed UnimplementedLearnServiceServer
// for forward compatibility
type LearnServiceServer interface {
	Hello(context.Context, *HelloRequest) (*HelloResponse, error)
	mustEmbedUnimplementedLearnServiceServer()
}

// UnimplementedLearnServiceServer must be embedded to have forward compatible implementations.
type UnimplementedLearnServiceServer struct {
}

func (UnimplementedLearnServiceServer) Hello(context.Context, *HelloRequest) (*HelloResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Hello not implemented")
}
func (UnimplementedLearnServiceServer) mustEmbedUnimplementedLearnServiceServer() {}

// UnsafeLearnServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LearnServiceServer will
// result in compilation errors.
type UnsafeLearnServiceServer interface {
	mustEmbedUnimplementedLearnServiceServer()
}

func RegisterLearnServiceServer(s grpc.ServiceRegistrar, srv LearnServiceServer) {
	s.RegisterService(&LearnService_ServiceDesc, srv)
}

func _LearnService_Hello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LearnServiceServer).Hello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LearnService_Hello_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LearnServiceServer).Hello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LearnService_ServiceDesc is the grpc.ServiceDesc for LearnService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LearnService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "LearnService",
	HandlerType: (*LearnServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Hello",
			Handler:    _LearnService_Hello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "learn.proto",
}
